In [ ]:
# Example using numpy

In [2]:
# import numpy library
import numpy as np

In [3]:
print("Numpy version:", np.__version__) #as of now, I have: Numpy version: 2.2.4

Numpy version: 2.2.4


In [4]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


In [5]:
# Perform basic operations
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))
print("Square root:", np.sqrt(arr))

Mean: 3.0
Sum: 15
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [6]:
# Create a 2D array
matrix = np.array([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

Matrix:
 [[1 2]
 [3 4]]


In [7]:
# Matrix transpose
print("Transpose:\n", matrix.T)

Transpose:
 [[1 3]
 [2 4]]


In [8]:
# Element-wise multiplication
print("Element-wise multiplication:\n", matrix * matrix)

Element-wise multiplication:
 [[ 1  4]
 [ 9 16]]


In [9]:
# Dot product
print("Dot product:\n", np.dot(matrix, matrix))

Dot product:
 [[ 7 10]
 [15 22]]
